- name: Create admins ssh dir
  file:
    path: /home/{{ item.username }}/.ssh
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0655

- name: Generate admins ssh keys
  shell: ssh-keygen -b 2048 -t rsa -f /home/{{ item.username }}/.ssh/id_rsa -q -N ""
  args:
    creates: /home/{{ item.username }}/.ssh/id_rsa
